CREATE TABLE t (a int) USING columnstore;
INSERT INTO t SELECT * FROM generate_series(1, 100);
EXPLAIN SELECT * FROM t;
INSERT INTO t SELECT * FROM generate_series(1, 200);
EXPLAIN SELECT * FROM t;
DROP TABLE t;
