CREATE TABLE t (a int DEFAULT NULL, b int) USING columnstore;
INSERT INTO t VALUES (DEFAULT, 1), (DEFAULT, 2);
INSERT INTO t VALUES (3, 3), (4, 4);
INSERT INTO t SELECT 5, 5;
SELECT * FROM t;
DROP TABLE t;

CREATE TABLE t (a int DEFAULT 3, b int) USING columnstore;
INSERT INTO t VALUES (DEFAULT, 1), (DEFAULT, 2);
INSERT INTO t VALUES (3, 3), (4, 4);
INSERT INTO t SELECT 5, 5;
SELECT * FROM t;
DROP TABLE t;

CREATE TABLE t (a int DEFAULT 1 + 2, b int) USING columnstore;
INSERT INTO t (b) VALUES (1), (2);
DROP TABLE t;

CREATE TABLE t (a int GENERATED ALWAYS AS IDENTITY, b int) USING columnstore;
INSERT INTO t (b) VALUES (1), (2);
INSERT INTO t (b) SELECT 3;
SELECT * FROM t;
DROP TABLE t;

-- Test RETURNING clause for INSERT.
CREATE TABLE t (a int) USING columnstore;
INSERT INTO t VALUES (123) RETURNING a + 1;
DROP TABLE t;

CREATE TABLE t (a int, b int DEFAULT 3) USING columnstore;
INSERT INTO t VALUES (1, DEFAULT), (2, DEFAULT) RETURNING *;
DROP TABLE t;
