CREATE TABLE t (a int);
INSERT INTO t VALUES (1);

BEGIN;
DECLARE c SCROLL CURSOR FOR SELECT a FROM t;
FETCH NEXT FROM c;
FETCH NEXT FROM c;
FETCH PRIOR FROM c;
COMMIT;

DROP TABLE t;

CREATE TABLE t (a int) USING columnstore;
INSERT INTO t VALUES (1);

BEGIN;
DECLARE c SCROLL CURSOR FOR SELECT a FROM t;
FETCH NEXT FROM c;
FETCH NEXT FROM c;
FETCH PRIOR FROM c;
COMMIT;

DROP TABLE t;
