CREATE TABLE t (c1 INT, c2 INT NOT NULL, c3 INT, c4 INT NOT NULL) using columnstore;

INSERT INTO t VALUES (1, 2, 3, 4);
INSERT INTO t (c1, c2) VALUES (11, 22);
SELECT * FROM t;

INSERT INTO t VALUES (1, NULL, 3, NULL);
INSERT INTO t VALUES (1, NULL, 3, 4);
INSERT INTO t VALUES (1, 2, 3, NULL);
INSERT INTO t (c2, c4) VALUES (2, NULL);
INSERT INTO t (c4, c2) VALUES (NULL, NULL);
INSERT INTO t (c4, c2) VALUES (44, 22);
SELECT * FROM t;

DROP TABLE t;
