CREATE TABLE t (c1 INT NOT NULL, c2 INT) using columnstore;

INSERT INTO t VALUES (1, 1);
INSERT INTO t (c1) VALUES (2);
SELECT * FROM t;

INSERT INTO t VALUES (NULL, 3);
INSERT INTO t (c1) VALUES (NULL);
SELECT * FROM t;

DROP TABLE t;
