FROM ubuntu:22.04

RUN yes | unminimize

RUN apt update \
 && apt install -y \
    bison \
    clang-format \
    cmake \
    curl \
    flex \
    g++ \
    gdb \
    git \
    libicu-dev \
    libreadline-dev \
    libssl-dev \
    locales \
    man \
    pkg-config \
    sudo \
    vim \
    zlib1g-dev \
 && rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8

RUN useradd -ms /bin/bash postgres \
 && echo 'postgres ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER postgres
WORKDIR /home/postgres
RUN echo 'source /workspaces/pg_mooncake/.devcontainer/.bashrc' >> .bashrc

RUN curl https://sh.rustup.rs | sh -s -- -y
ENV PATH="/home/postgres/.cargo/bin:${PATH}"
RUN cargo install sccache

ENV PATH="/usr/local/pgsql/bin:${PATH}"
RUN curl https://ftp.postgresql.org/pub/source/v17.2/postgresql-17.2.tar.bz2 | bzip2 -d | tar x \
 && cd postgresql-17.2 \
 && ./configure --enable-cassert --enable-debug CFLAGS='-ggdb3' \
 && make -j$(nproc) \
 && sudo make install \
 && sudo chown -R postgres:postgres /usr/local/pgsql \
 && initdb -D /usr/local/pgsql/data
RUN echo '\\i /workspaces/pg_mooncake/.devcontainer/.psqlrc' > .psqlrc
