CREATE TABLE t (a int) USING columnstore;
ALTER TABLE t SET ACCESS METHOD heap;
ALTER TABLE t SET ACCESS METHOD columnstore;
ALTER TABLE t ADD COLUMN b int;
DROP TABLE t;

CREATE TABLE t (a int);
ALTER TABLE t SET ACCESS METHOD heap;
ALTER TABLE t SET ACCESS METHOD columnstore;
DROP TABLE t;
