LOAD 'pg_mooncake';

CREATE TABLE s (a int);
INSERT INTO s VALUES (1), (2), (3);

CREATE TABLE t AS SELECT * FROM s;
SELECT * FROM t;
DROP TABLE t;

CREATE TABLE t USING columnstore AS SELECT * FROM s;

DROP TABLE s;
