[package]
name = "delta"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
deltalake = "0.20.0"
tokio = "1.28"
serde_json = "1.0"

[build-dependencies]
cxx-build = "1.0"
