[package]
name = "delta"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
deltalake = {version = "0.24", features = ["s3"] }
tokio = "1.41"
serde_json = "1.0"

[build-dependencies]
cxx-build = "1.0"
